@startuml vente formations

left to right direction

actor "utilisateur connecté" as USER_CONNECTED
actor "utilisateur non connecté" as USER


USER <|-- USER_CONNECTED


package "application vente formations" {
    usecase "valider une commande" as CONFIRM_ORDER
    usecase "afficher ses commandes" as DISPLAY_ORDERS
    usecase "afficher les formations" as DISPLAY_COURSES
    usecase "gérer son panier" as MANAGE_CART
    usecase "se connecter" as CONNECT
}


USER -- DISPLAY_COURSES

USER_CONNECTED -- CONFIRM_ORDER
USER_CONNECTED -- DISPLAY_ORDERS
USER_CONNECTED -- MANAGE_CART

DISPLAY_ORDERS ..> CONNECT : <<include>>
CONFIRM_ORDER ..> CONNECT : <<include>>
MANAGE_CART ..> CONNECT : <<include>>

@enduml
