@startuml

abstract class Person {
    - string firstname
    - string lastname
}

class User {
    - string password
    - string login
}

class Customer {
    - string address
    - string email
    - string phoneNumber
}

Person <|-- User
Person <|-- Customer

class Course {
    - string name
    - string description
    - int durationDays
    - boolean isOnline
    - boolean isOnSite
    - decimal price
}

class Cart {
    - id : int
}

Cart "*" o-- "1..*" Course
User "1" --> "0..1" Cart

class Order {
    - date orderDate
    - decimal totalAmount
}

Order "*" --> "1..*" Course
Order "1..*" --> "1" Customer
User "1" --> "0..*" Order

@enduml
